PDF 최적화: 누락된 정보가 있어도 미리보기가 가능하도록 수정
EntryDSM/Husky pull request #39
Opened 2020-09-14 03:05 UTC by LumpKim

# PDF 최적화: 누락된 정보가 있어도 미리보기가 가능하도록 수정
## 목적
### 요약
난잡하던 기존 코드를 줄이고 User 엔티티 내 isEmpty(), isCommonApply() 등 여러 util 메서드를 추가하여 클린 코드를 작성할 수 있도록 수정했습니다. 
### 상세
- 이미지 삽입 로직 추가: `ImageService.getObject()`로 byte[] 형식의 이미지를 가공/삽입
- Null Check 강화: 미리보기 시 특정 필드가 채워져 있지 않을 경우 발생하던 NullPointerException 수정
- 졸업연월 삽입 로직 추가(졸업자 졸업 예정월 기재 여부 결정은 보류)
- `User` 엔티티에 util 메서드 추가(`is___Empty()`, `is___Apply()`, etc)
- `SecurityConfig`에서 `X-Frame-Options` 허용: 프론트 PDF 뷰어에서 Iframe 이용으로 인해 발생하는 '액세스 거부됨' 문제 해결
  - 내장 Tomcat 설정 기본값이 DENY로 되어 있어 발생한 문제
## 영향을 미치는 부분
- 5xx 에러가 자주 발생하던 고질적 문제점을 해결하였습니다.
- `User` 엔티티에 여러 util 클래스가 추가되었습니다.

2020-09-14 05:07 UTC, huewilliams requested changes

2020-09-14 05:07 UTC, huewilliams commented on src/main/java/kr/hs/entrydsm/husky/domain/pdf/service/PDFExportServiceImpl.java
> +    private boolean isGED(User user) {
isGED 메서드와 isCommonApply 메서드는 User Entity에 위치해야 하지 않을까요?

2020-09-14 05:07 UTC, huewilliams commented on src/main/java/kr/hs/entrydsm/husky/domain/pdf/service/PDFExportServiceImpl.java
> +    private boolean isFinalSubmitRequired(User user) {
이 메서드 또한 User Entity에 위치해야 한다고 생각합니다.

2020-09-14 05:07 UTC, huewilliams commented on src/main/java/kr/hs/entrydsm/husky/domain/pdf/service/PDFExportServiceImpl.java
> +        String objectKey = (user.isPhotoEmpty()) ? "default.png" : user.getUserPhoto();
이건 프로세스 상 의문점인데, 만약 최종제출 이후 이미지가 없어 default.png로 pdf가 생성되면 유저는 어떻게 해야 할까요? 최종제출 된 상태 이므로 이미지가 비어 있는 걸 확인해도 고칠 방법이 없을 것 같아요. (전화하는 것 이외에는..)

2020-09-14 08:10 UTC, LumpKim commented on src/main/java/kr/hs/entrydsm/husky/domain/pdf/converter/ApplicationInfoConverter.java
>          values.put("isDj", toBallotBox(user.getIsDaejeon()));
변수 이름을 `isDj`로 표기한 이유는 `${isDaejeon}`으로 표기할 경우 다음 페이지로 넘어가 레이아웃이 깨지기 때문입니다. 부득이하게 페이지가 넘어가지 않도록 줄이다 보니 `${isDj}`로 차용하게 되었습니다.

2020-09-14 08:12 UTC, LumpKim commented on src/main/java/kr/hs/entrydsm/husky/domain/pdf/converter/ApplicationInfoConverter.java
> +    private static void setPersonalInfo(Map<String, String> values, User user) {
넵 수정하도록 하겠습니다.

2020-09-14 08:13 UTC, LumpKim commented on src/main/java/kr/hs/entrydsm/husky/domain/pdf/converter/ApplicationInfoConverter.java
> +            if (isSchoolNameLongerThan10Char(schoolName)) {
학교 이름이 10글자가 넘어가는 경우 한 칸씩 띄우게 되면 줄넘김이 발생해 페이지 레이아웃이 변형되기 때문입니다.

2020-09-14 08:14 UTC, LumpKim commented on src/main/java/kr/hs/entrydsm/husky/domain/pdf/service/PDFExportServiceImpl.java
> +    private boolean isFinalSubmitRequired(User user) {
수정하도록 하겠습니다.

2020-09-14 08:19 UTC, LumpKim commented on src/main/java/kr/hs/entrydsm/husky/domain/pdf/service/PDFExportServiceImpl.java
> +    private boolean isGED(User user) {
의견 감사드립니다. 적극적으로 반영하도록 하겠습니다.

2020-09-14 08:21 UTC, LumpKim commented on src/main/java/kr/hs/entrydsm/husky/domain/pdf/service/PDFExportServiceImpl.java
> +        String objectKey = (user.isPhotoEmpty()) ? "default.png" : user.getUserPhoto();
해당 PDF 생성 메서드는 미리보기 및 최종제출 모두 공용으로 사용하는 메서드입니다. 말씀하신 상황이 발생하지 않도록 최종제출 이전에 지원자 사진이 있는지 확인하는 로직이 구성하도록 하겠습니다. 물론 최종제출 이후 기재 정보 수정과 같은 경우에는 말씀하신 것 처럼 전화/채팅 문의가 필요한 것은 사실입니다.

2020-09-14 08:31 UTC, LumpKim commented on src/main/java/kr/hs/entrydsm/husky/domain/pdf/converter/ApplicationInfoConverter.java
> +    private static void setPersonalInfo(Map<String, String> values, User user) {
수정하여 Commit#025952에 반영하였습니다.

2020-09-14 08:35 UTC, LumpKim commented on src/main/java/kr/hs/entrydsm/husky/domain/pdf/service/PDFExportServiceImpl.java
> +    private boolean isGED(User user) {
수정하여 [Commit#726abe](https://github.com/EntryDSM/Husky/pull/39/commits/726abe1876eefda66ce1ee170ecec82ffcb53d65)에 반영하였습니다.

2020-09-14 09:53 UTC, LumpKim commented on src/main/java/kr/hs/entrydsm/husky/domain/pdf/service/PDFExportServiceImpl.java
> +    private boolean isFinalSubmitRequired(User user) {
수정하여 [Commit#5f023d](https://github.com/EntryDSM/Husky/pull/39/commits/5f023dc7f2cf41a5b9aab608d4de2e89c3362742)에 반영하였습니다.

2020-09-14 10:58 UTC, huewilliams approved these changes
피드백 반영 좋아여. 수고하셨습니다.

2020-09-14 23:42 UTC, LumpKim commented on src/main/java/kr/hs/entrydsm/husky/domain/pdf/converter/ApplicationInfoConverter.java
> +        String graduatedYYYY = "";
동의합니다. 수정 후 업로드 하도록 하겠습니다.

2020-09-14 23:47 UTC, LumpKim commented on src/main/java/kr/hs/entrydsm/husky/domain/pdf/converter/ApplicationInfoConverter.java
> +        String graduatedYYYY = "";
수정하여 [Commit#fdfd94](https://github.com/EntryDSM/Husky/pull/39/commits/fdfd948a67056adac3e96cb9815b4b86060ac661)에 반영했습니다.

2020-09-15 01:22 UTC, LeagueLugas approved these changes

2020-09-15 02:32 UTC, merged