GET Status API 분리
EntryDSM/Husky pull request #77
Opened 2020-10-12 07:14 UTC by huewilliams

# GET Status API 분리
## 목적
### 요약
* GET Status API 분리(마이페이지, 합격여부)
### 상세
**GET Status API 분리(마이페이지, 합격여부)**
기존의 `GET/users/me/status` API는 마이페이지에서 사용되는 상태 정보와 합격 확인 페이지에서 사용되는 합격 여부가 모두 포함되어있었다. 하지만 마이페이지에서 개발자 도구를 이용하여 합격 날짜 전에 미리 합격 여부를 확인할 수 있다는 결함이 있어서 두 개의 API로 분리했다.
* `GET/users/me/status` : 마이페이지 상태 정보 반환 API
* `GET/users/me/status/pass` : 합격여부 반환 API
## 영향을 미치는 부분
API Docs(업데이트 완료), 프론트엔드 합격여부 페이지 사용 API 변경(프론트 팀에게 전달 필요)
## 참조(선택)
#76 해결

2020-10-12 07:35 UTC, LeagueLugas approved these changes

2020-10-13 00:08 UTC, LumpKim requested changes
결과 발표일 이전까지 쿼리 결과를 공개하지 않는 로직이 누락되어 있습니다.
수정 부탁드립니다.

2020-10-13 00:08 UTC, LumpKim commented on src/main/java/kr/hs/entrydsm/husky/domain/user/service/status/UserStatusServiceImpl.java
> +
그래서 결과 발표일 이전까지 쿼리 결과를 공개하지 않는 로직은 어디 있는지 알 수 있을까요?

2020-10-13 00:08 UTC, LumpKim commented on src/main/java/kr/hs/entrydsm/husky/domain/user/service/status/UserStatusServiceImpl.java
> +
사견으로는 Redis 일정 정보를 불러오는 게 맞다고 생각합니다.

2020-10-13 02:22 UTC, huewilliams commented on src/main/java/kr/hs/entrydsm/husky/domain/user/service/status/UserStatusServiceImpl.java
> +
Redis로 일정 정보를 불러왔으며 결과 발표가 1차 합격과 최종 합격 두 가지로 나눠져 있기에 일정에 따라 API를 구성했습니다.

2020-10-13 02:57 UTC, LumpKim requested changes

2020-10-13 02:57 UTC, LumpKim commented on src/main/java/kr/hs/entrydsm/husky/domain/user/exception/NotStartedScheduleException.java
> +public class NotStartedScheduleException extends BusinessException {
Exception 네이밍 순서가 이상해 보입니다. 아래 `ScheduleNotFoundException`과 같이 주어가 앞에 와야 하지 않을까요?
ex) `ScheduleNotStartedException` 등

2020-10-13 02:57 UTC, LumpKim commented on src/main/java/kr/hs/entrydsm/husky/domain/user/service/status/UserStatusServiceImpl.java
> +        if(LocalDateTime.now().compareTo(schedule.getStartDate()) < 0)
IDE 상에서 코드 스타일 정렬 부탁드립니다.

2020-10-13 02:57 UTC, LumpKim commented on src/main/java/kr/hs/entrydsm/husky/domain/user/service/status/UserStatusServiceImpl.java
> +        if(LocalDateTime.now().compareTo(schedule.getStartDate()) < 0)
IDE 상에서 코드 스타일 정렬 부탁드립니다.

2020-10-13 02:57 UTC, LumpKim commented on src/main/java/kr/hs/entrydsm/husky/domain/user/service/status/UserStatusServiceImpl.java
> +        if(LocalDateTime.now().compareTo(schedule.getStartDate()) < 0)
중복되는 조건문을 별도의 함수로 분리하여 작성한다면 가독성이 향상될 것 같습니다.

2020-10-13 02:57 UTC, LumpKim commented on src/main/java/kr/hs/entrydsm/husky/domain/user/service/status/UserStatusServiceImpl.java
> +                .build();
개인적인 의견입니다. 꼭 적용하실 필요는 없습니다.
98번 라인에서 변수에 할당하지 말고 optional 메서드 체이닝을 적용하면 어떨까요?

2020-10-13 02:57 UTC, LumpKim commented on src/main/java/kr/hs/entrydsm/husky/global/error/exception/ErrorCode.java
> +    SCHEDULE_NOT_FOUND(404, "I404-1", "Schedule Not Found"),
문서화가 완료되었는지 궁금합니다.

2020-10-13 03:16 UTC, huewilliams commented on src/main/java/kr/hs/entrydsm/husky/domain/user/exception/NotStartedScheduleException.java
> +public class NotStartedScheduleException extends BusinessException {
알겠습니다.

2020-10-13 03:27 UTC, huewilliams commented on src/main/java/kr/hs/entrydsm/husky/domain/user/service/status/UserStatusServiceImpl.java
> +        if(LocalDateTime.now().compareTo(schedule.getStartDate()) < 0)
넹

2020-10-13 03:48 UTC, huewilliams commented on src/main/java/kr/hs/entrydsm/husky/domain/user/service/status/UserStatusServiceImpl.java
> +        if(LocalDateTime.now().compareTo(schedule.getStartDate()) < 0)
별도 함수로 분리했습니다.

2020-10-13 03:49 UTC, huewilliams commented on src/main/java/kr/hs/entrydsm/husky/global/error/exception/ErrorCode.java
> +    SCHEDULE_NOT_FOUND(404, "I404-1", "Schedule Not Found"),
프론트 팀에게 수정사항을 알려주기 전 문서화 작업을 먼저 할 예정입니다.

2020-10-13 04:42 UTC, LumpKim commented on src/main/java/kr/hs/entrydsm/husky/global/error/exception/ErrorCode.java
> +    SCHEDULE_NOT_FOUND(404, "I404-1", "Schedule Not Found"),
문서화 후에 이 대화를 닫아주세요.

2020-10-13 04:45 UTC, huewilliams commented on src/main/java/kr/hs/entrydsm/husky/global/error/exception/ErrorCode.java
> +    SCHEDULE_NOT_FOUND(404, "I404-1", "Schedule Not Found"),
문서화 작업도 완료되었습니다.

2020-10-13 04:45 UTC, LumpKim requested changes

2020-10-13 04:45 UTC, LumpKim commented on src/main/java/kr/hs/entrydsm/husky/domain/user/exception/ProcessNotCompletedException.java
>          super(ErrorCode.NOT_COMPLETED_PROCESS);
에러 코드도 같이 변경해야 하지 않을까요?

2020-10-13 04:45 UTC, LumpKim commented on src/main/java/kr/hs/entrydsm/husky/domain/user/exception/ScheduleNotStartedException.java
> +    public ScheduleNotStartedException() { super(ErrorCode.NOT_STARTED_SCHEDULE); }
에러 코드도 같이 수정해 주세요.

2020-10-13 04:45 UTC, LumpKim commented on src/main/java/kr/hs/entrydsm/husky/domain/user/service/status/UserStatusServiceImpl.java
> +        checkSchedule("notice");
checkSchedule이라는 별도 함수로 구분한 것은 좋으나 필요한 schedule id를 상수로 만들어 관리했으면 좋겠습니다.

2020-10-13 04:48 UTC, huewilliams commented on src/main/java/kr/hs/entrydsm/husky/domain/user/exception/ScheduleNotStartedException.java
> +    public ScheduleNotStartedException() { super(ErrorCode.NOT_STARTED_SCHEDULE); }
네

2020-10-13 04:48 UTC, huewilliams commented on src/main/java/kr/hs/entrydsm/husky/domain/user/exception/ProcessNotCompletedException.java
>          super(ErrorCode.NOT_COMPLETED_PROCESS);
에러 코드도 변경해야 될 것 같습니다.

2020-10-13 04:52 UTC, huewilliams commented on src/main/java/kr/hs/entrydsm/husky/domain/user/service/status/UserStatusServiceImpl.java
> +        checkSchedule("notice");
동의합니다. PDF 로직에서도 상수 값들이 있었는데, 그것들도 상수로 관리하는 게 좋지 않을까요?

2020-10-13 04:54 UTC, LumpKim commented on src/main/java/kr/hs/entrydsm/husky/domain/user/service/status/UserStatusServiceImpl.java
> +        checkSchedule("notice");
좋은 의견인 것 같습니다. master 브랜치에서 별도 브랜치를 생성하여 본 브랜치에 신규 PR을 생성하겠습니다.

2020-10-13 05:07 UTC, LumpKim approved these changes

2020-10-13 05:18 UTC, merged